export const CREATE_STORY_ERROR = 'CREATE_STORY_ERROR';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';

export const UPDATE_STORY_ERROR = 'UPDATE_STORY_ERROR';
export const UPDATE_STORY_SUCCESS = 'UPDATE_STORY_SUCCESS';

export const DELETE_STORY_ERROR = 'DELETE_STORY_ERROR';
export const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';