export CREATE_STORY_ERROR = 'CREATE_STORY_ERROR';
export CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';

export UPDATE_STORY_ERROR = 'UPDATE_STORY_ERROR';
export UPDATE_STORY_SUCCESS = 'UPDATE_STORY_SUCCESS';

export DELETE_STORY_ERROR = 'DELETE_STORY_ERROR';
export DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';